version: '3'
services:
    nginx:
        build: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./html:/app/test1
            - ./nginx/sitio.conf:/etc/nginx/conf.d/sitio.conf
            - ./nginx/entrypoint.sh:/sbin/entrypoint.sh

            - ./nginx/wildcert.pem:/certs/wildcert.pem
            - ./nginx/wildkey.key:/certs/wildkey.key

            - ./symfony:/app/symfony
            - ./nginx/symfony.conf:/etc/nginx/conf.d/symfony.conf

    app:
        build: phpDrupal
        volumes:
        - ./html:/app/test1
        - ./phpDrupal/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
        - ./symfony:/app/symfony

    db:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=abc123..
            - MYSQL_DATABASE=tarefa
            - MYSQL_USER=a22yagormTarefa
            - MYSQL_PASSWORD=a22yagormTarefaPW
        volumes:
            - baseDatos:/var/lib/mysql
            - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
    baseDatos: